spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL:}
    username: ${USER_NAME:}
    password: ${PASSWORD:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  server:
    port: 8080
    servlet:
      context-path: /auth